config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  resources :items
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :find_item, only: [:show, :edit, :update, :destroy]
    
    def index
        @items = Item.all.order("created_at DESC")
        @date = Time.now.strftime("%d.%m.%y - %H:%M Uhr")
    end
    
    def new
        @item = Item.new
    end
    
    def create
        @item = Item.new(item_params)
        if @item.save
            redirect_to root_path
        else
            render 'new'
    end
end
    def show
    end
    
    def destroy
        @item.destroy
        redirect_to root_path
    end
    
    def edit
    end
    
    def update
        if @item.update(item_params)
            redirect_to root_path
        else render 'edit'
        end
    end
    
    private
    def item_params
        params.require(:item).permit(:bloodpressure, :heartrate, :description)
    end
    
    def find_item
        @item = Item.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%= link_to "Zurück", root_path, :class => "btn btn-default"%><br><br>
<h1>Wert Ändern</h1>
<%= simple_form_for @item do |f| %>
  <%= f.input :bloodpressure, label: "Blutdruck", placeholder: "XXX/XX"%>
  <%= f.input :heartrate, label: "Herzfrequenz" %>
  <%= f.input :description, label: "Bemerkungen" %>
  <%= f.button :submit, "Speichern"%>
<% end %>

app/views/items/index.html.erb
<p style="font-size:10px; color: #cccccc;"><%= @date %></p>
<h1>Mein Blutdruck:</h1><br>
<%= link_to "Neuen Wert Eingeben", new_item_path, :class => "btn btn-default" %><br>
<hr>
<hr>
<% @items.each do |item| %>
<h5><%= link_to item do %><i class="fa fa-pencil" aria-hidden="true"></i>
<% end %> <%= item.created_at.strftime("%d.%m.%y - %H:%M Uhr") %> : <strong><%= item.bloodpressure %></strong> : <strong><%= item.heartrate %></strong>BPM : Info:<%= item.description %></h5>
<% end %>

app/views/items/new.html.erb
<h1>Neuen Wert Anlegen</h1>
<%= simple_form_for @item do |f| %>
  <%= f.input :bloodpressure, label: "Blutdruck", placeholder: "XXX/XX"%>
  <%= f.input :heartrate, label: "Herzfrequenz" %>
  <%= f.input :description, label: "Bemerkungen" %>
  <%= f.button :submit, "Speichern"%>
<% end %>

app/views/items/show.html.erb
<%= link_to "Zurück", root_path, :class => "btn btn-default"%><br><br>
<h4>Mein Blutdruck am <%= @item.created_at.strftime("%d.%m.%y - %H:%M Uhr") %></h4>
<hr>
<h2>Blutdruck: <%= @item.bloodpressure %></h2>
<h2>Herzfrequenz: <%= @item.heartrate %></h2>
<h2>Bemerkung: <%= @item.description %></h2>
<hr>
<h1><%= link_to edit_item_path do %>
<i class="fa fa-pencil" aria-hidden="true"></i>
<% end %> | <%= link_to item_path(@item), method: :delete, data: { confirm: "Bist Du sicher?" } do %>
<i class="fa fa-trash-o" aria-hidden="true"></i>
<% end %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
</head>
<body>
  
<div class="container" style="width: 33%; padding-top: 50px;">
<%= yield %>
</div>

</body>
</html>